#!/bin/bash
domain=$(cat /etc/xray/domain)

until [[ $user =~ ^[a-zA-Z0-9_]+$ && ${CLIENT_EXISTS} == '0' ]]; do
echo -e "\u001B[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001B[0m"
echo -e "\e[0;41;36m      Add Vmess Account      \e[0m"
echo -e "\u001B[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001B[0m"

read -rp "User: " -e user
CLIENT_EXISTS=$(grep -w $user /etc/xray/config.json | wc -l)

if [[ ${CLIENT_EXISTS} == '1' ]]; then
clear
echo -e "\u001B[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001B[0m"
echo -e "\e[0;41;36m      Add Vmess Account      \e[0m"
echo -e "\u001B[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001B[0m"
echo ""
echo "A client with the specified name was already created, please choose another name."
echo ""
echo -e "\u001B[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001B[0m"
read -n 1 -s -r -p "Press any key to back on menu"
menu
fi
done

uuid=$(cat /proc/sys/kernel/random/uuid)
read -p "Expired (days): " masaaktif
exp=`date -d "$masaaktif days" +"%Y-%m-%d"`
sed -i '/#vmess$/a### '"$user $exp"'\
},{"id": "'""$uuid""'","alterId": '"0"',"email": "'""$user""'"' /etc/xray/config.json

asu=`cat<<EOF
      {
      "v": "2",
      "ps": "${user}",
      "add": "${domain}",
      "port": "443",
      "id": "${uuid}",
      "aid": "0",
      "net": "ws",
      "path": "/vmess",
      "type": "none",
      "host": "${domain}",
      "tls": "tls"
}
EOF`
ask=`cat<<EOF
      {
      "v": "2",
      "ps": "${user}",
      "add": "${domain}",
      "port": "80",
      "id": "${uuid}",
      "aid": "0",
      "net": "ws",
      "path": "/vmess",
      "type": "none",
      "host": "${domain}",
      "tls": "none"
}
EOF`

vmess_base641=$( base64 -w 0 <<< $vmess_json1)
vmess_base642=$( base64 -w 0 <<< $vmess_json2)

vmesslink1="vmess://$(echo $asu | base64 -w 0)"
vmesslink2="vmess://$(echo $ask | base64 -w 0)"

systemctl restart xray > /dev/null 2>&1
service cron restart > /dev/null 2>&1
clear
echo -e "\u001B[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001B[0m"
echo -e "\e[0;41;36m        Vmess Account        \e[0m"
echo -e "\u001B[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001B[0m"
echo -e "Remarks        : ${user}"
echo -e "Domain         : ${domain}"
echo -e "Port TLS       : 443"
echo -e "Port none TLS  : 80"
echo -e "id             : ${uuid}"
echo -e "alterId        : 0"
echo -e "Security       : auto"
echo -e "Network        : ws"
echo -e "Path           : /vmess"
echo -e "\u001B[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001B[0m"
echo -e "Link TLS       : ${vmesslink1}"
echo -e "\u001B[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001B[0m"
echo -e "Link none TLS  : ${vmesslink2}"
echo -e "\u001B[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001B[0m"
echo -e "Expired On     : $exp"
echo -e "\u001B[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001B[0m"
echo ""
read -n 1 -s -r -p "Press any key to back on menu"
menu