#!/bin/bash
domain=$(cat /etc/xray/domain)

until [[ $user =~ ^[a-zA-Z0-9_]+$ && ${user_EXISTS} == '0' ]]; do
echo -e "\u001B[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001B[0m"
echo -e "E[0;41;36m           TROJAN ACCOUNT          E[0m"
echo -e "\u001B[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001B[0m"

read -rp "User: " -e user
user_EXISTS=$(grep -w $user /etc/xray/config.json | wc -l)

if [[ ${user_EXISTS} == '1' ]]; then
clear
echo -e "\u001B[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001B[0m"
echo -e "E[0;41;36m           TROJAN ACCOUNT          E[0m"
echo -e "\u001B[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001B[0m"
echo ""
echo "A client with the specified name was already created, please choose another name."
echo ""
echo -e "\u001B[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001B[0m"
read -n 1 -s -r -p "Press any key to back on menu"
menu
fi
done

uuid=$(cat /proc/sys/kernel/random/uuid)
read -p "Expired (days): " masaaktif
exp=`date -d "$masaaktif days" +"%Y-%m-%d"`
sed -i '/#trojanws$/a#! '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json

trojanlink="trojan://${uuid}@isi_bug_disini:443?path=%2Ftrojan-ws&security=tls&host=${domain}&type=ws&sni=${domain}#${user}"
trojanlink2="trojan://${uuid}@isi_bug_disini:80?path=%2Ftrojan-ws&security=none&host=${domain}&type=ws#${user}"

systemctl restart xray
clear
echo -e "\u001B[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001B[0m"
echo -e "E[0;41;36m           TROJAN ACCOUNT           E[0m"
echo -e "\u001B[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001B[0m"
echo -e "Remarks        : ${user}"
echo -e "Host/IP        : ${domain}"
echo -e "Port TLS       : 443"
echo -e "Port none TLS  : 80"
echo -e "Key            : ${uuid}"
echo -e "Path           : /trojan-ws"
echo -e "\u001B[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001B[0m"
echo -e "Link TLS       : ${trojanlink}"
echo -e "\u001B[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001B[0m"
echo -e "Link none TLS  : ${trojanlink2}"
echo -e "\u001B[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001B[0m"
echo -e "Expired On     : $exp"
echo -e "\u001B[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001B[0m"
echo ""
read -n 1 -s -r -p "Press any key to back on menu"
menu