#!/bin/bash

# ====== CONFIG ======
TELEGRAM_BOT_TOKEN="ISI_TOKEN_BOT_LU"
TELEGRAM_CHAT_ID="ISI_CHAT_ID_LU"
S3_REMOTE="xrayonly:xrayonly/backup"
CONFIG_FILE="/etc/xray/config.json"
HASH_FILE="/var/log/xray_backup_hash"
# ====================

DATE=$(date +%F-%H%M)
BACKUP_NAME="xray-backup-$DATE.zip"
TMP="/tmp/$BACKUP_NAME"

set -o pipefail

# Pastikan config ada
[ ! -f "$CONFIG_FILE" ] && exit 1

CURRENT_HASH=$(sha256sum "$CONFIG_FILE" | awk '{print $1}')
[ -f "$HASH_FILE" ] && OLD_HASH=$(cat "$HASH_FILE")

# Exit hanya kalau:
# - BUKAN force telegram
# - DAN hash sama
if [ "$SEND_TELEGRAM" != "1" ] && [ "$CURRENT_HASH" == "$OLD_HASH" ]; then
    exit 0
fi

systemctl stop vnstat

zip -r "$TMP" /etc/xray /var/lib/vnstat > /dev/null 2>&1
ZIP_STATUS=$?

systemctl start vnstat

# Kalau zip gagal, exit
if [ "$ZIP_STATUS" -ne 0 ]; then
    rm -f "$TMP"
    exit 1
fi

rclone copy "$TMP" "$S3_REMOTE"
RCLONE_STATUS=$?

# Kalau upload gagal, jangan update hash
if [ "$RCLONE_STATUS" -ne 0 ]; then
    rm -f "$TMP"
    exit 1
fi

# Update hash hanya kalau backup sukses
echo "$CURRENT_HASH" > "$HASH_FILE"

# Telegram hanya kalau dipanggil cron dengan SEND_TELEGRAM=1
if [ "$SEND_TELEGRAM" = "1" ]; then
    curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendDocument" \
      -F chat_id="$TELEGRAM_CHAT_ID" \
      -F document=@"$TMP" \
      -F caption="Backup XRAY + VNSTAT $DATE" \
      > /dev/null
fi

rm -f "$TMP"