#!/bin/bash

NC='\e[0m'
DEFBOLD='\e[39;1m'
RB='\e[31;1m'
GB='\e[32;1m'
YB='\e[33;1m'
BB='\e[34;1m'
MB='\e[35;1m'
CB='\e[35;1m'
WB='\e[37;1m'

clear
echo -n >/tmp/other.txt
data=($(grep '^#!' /etc/xray/config.json | cut -d ' ' -f 2 | sort | uniq))

echo -e "${BB}————————————————————————————————————————————————————${NC}"
echo -e "              ${WB}Trojan User Login Account${NC}             "
echo -e "${BB}————————————————————————————————————————————————————${NC}"

for akun in "${data[@]}"; do
if [[ -z "$akun" ]]; then
akun="Tidak Ada"
fi

echo -n >/tmp/iptrojan.txt

data2=($(grep "email: $akun" /var/log/xray/access.log | tail -n 500 | awk '{print $4}' | sed 's/tcp://g' | cut -d ':' -f1 | sort | uniq))

for ip in "${data2[@]}"; do
echo "$ip" >>/tmp/iptrojan.txt
done

jum=$(cat /tmp/iptrojan.txt)

if [[ -z "$jum" ]]; then
echo >/dev/null
else
jum2=$(cat /tmp/iptrojan.txt | nl)
echo "user : $akun"
echo "$jum2"
echo -e "${BB}————————————————————————————————————————————————————${NC}"
fi

rm -rf /tmp/iptrojan.txt
done

rm -rf /tmp/other.txt
echo ""
read -n 1 -s -r -p "Press any key to back on menu"
menu