#!/bin/bash

# ==========================================
# Color
red='\e[1;31m'
green='\e[0;32m'
yellow='\e[1;33m'
NC='\e[0m'
# ==========================================

clear
domain=$(cat /etc/xray/domain)

echo -e "[ ${green}INFO${NC} ] Start"
sleep 0.5

systemctl stop nginx

Cek=$(lsof -i:80 | awk 'NR==2 {print $1}')
if [[ -n "$Cek" ]]; then
    echo -e "[ ${yellow}WARNING${NC} ] Port 80 used by $Cek"
    systemctl stop $Cek
    sleep 1
fi

echo -e "[ ${green}INFO${NC} ] Starting renew cert for domain: $domain"
sleep 1

# ==============================
# ISSUE CERT
# ==============================
/root/.acme.sh/acme.sh --set-default-ca --server letsencrypt >/dev/null 2>&1
/root/.acme.sh/acme.sh --issue -d $domain --standalone -k ec-256 --force >/tmp/acme.log 2>&1

if [[ $? -ne 0 ]]; then
    if grep -q "rateLimited" /tmp/acme.log; then
        echo -e "[ ${red}ERROR${NC} ] Let's Encrypt Rate Limit Hit!"
        echo -e "[ ${yellow}INFO${NC} ] Try again after limit reset (168h window)"
    elif grep -q "NXDOMAIN" /tmp/acme.log; then
        echo -e "[ ${red}ERROR${NC} ] Domain not pointing to this VPS!"
    elif grep -q "timeout" /tmp/acme.log; then
        echo -e "[ ${red}ERROR${NC} ] Connection Timeout (Firewall/DNS Issue)"
    else
        echo -e "[ ${red}ERROR${NC} ] Certificate issue failed!"
        echo -e "[ ${yellow}INFO${NC} ] Check: /tmp/acme.log"
    fi

    systemctl start nginx
    [[ -n "$Cek" ]] && systemctl start $Cek
    echo ""
    read -n 1 -s -r -p "Press any key to back on menu"
    menu
    exit
fi

# =============================
# INSTALL CERT ONLY IF SUCCESS
# ==============================
/root/.acme.sh/acme.sh --installcert -d $domain \
--fullchainpath /etc/xray/xray.crt \
--keypath /etc/xray/xray.key \
--ecc --force >/dev/null 2>&1

echo -e "[ ${green}INFO${NC} ] Renew cert success!"
sleep 1

[[ -n "$Cek" ]] && systemctl start $Cek
systemctl start nginx
systemctl restart xray

echo -e "[ ${green}INFO${NC} ] All finished..."
echo ""
read -n 1 -s -r -p "Press any key to back on menu"
menu